# Generated by Django 3.2.19 on 2023-07-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='priority',
            field=models.CharField(choices=[('LP', 'Low Priority'), ('MP', 'Medium Priority'), ('TP', 'Top Priority')], default='Medium Priority', max_length=50),
        ),
        migrations.AlterField(
            model_name='taskmanager',
            name='status',
            field=models.CharField(choices=[('TBD', 'Not Started'), ('IPG', 'In Progress'), ('D', 'Done')], default='Not Started', max_length=50),
        ),
    ]
